/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AAppelFonctionExpr7 extends PExpr7
{
    private TIdentif _identif_;
    private TParentheseGauche _parentheseGauche_;
    private PListeExpr _listeExpr_;
    private TParentheseDroite _parentheseDroite_;

    public AAppelFonctionExpr7()
    {
        // Constructor
    }

    public AAppelFonctionExpr7(
        @SuppressWarnings("hiding") TIdentif _identif_,
        @SuppressWarnings("hiding") TParentheseGauche _parentheseGauche_,
        @SuppressWarnings("hiding") PListeExpr _listeExpr_,
        @SuppressWarnings("hiding") TParentheseDroite _parentheseDroite_)
    {
        // Constructor
        setIdentif(_identif_);

        setParentheseGauche(_parentheseGauche_);

        setListeExpr(_listeExpr_);

        setParentheseDroite(_parentheseDroite_);

    }

    @Override
    public Object clone()
    {
        return new AAppelFonctionExpr7(
            cloneNode(this._identif_),
            cloneNode(this._parentheseGauche_),
            cloneNode(this._listeExpr_),
            cloneNode(this._parentheseDroite_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAppelFonctionExpr7(this);
    }

    public TIdentif getIdentif()
    {
        return this._identif_;
    }

    public void setIdentif(TIdentif node)
    {
        if(this._identif_ != null)
        {
            this._identif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identif_ = node;
    }

    public TParentheseGauche getParentheseGauche()
    {
        return this._parentheseGauche_;
    }

    public void setParentheseGauche(TParentheseGauche node)
    {
        if(this._parentheseGauche_ != null)
        {
            this._parentheseGauche_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentheseGauche_ = node;
    }

    public PListeExpr getListeExpr()
    {
        return this._listeExpr_;
    }

    public void setListeExpr(PListeExpr node)
    {
        if(this._listeExpr_ != null)
        {
            this._listeExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listeExpr_ = node;
    }

    public TParentheseDroite getParentheseDroite()
    {
        return this._parentheseDroite_;
    }

    public void setParentheseDroite(TParentheseDroite node)
    {
        if(this._parentheseDroite_ != null)
        {
            this._parentheseDroite_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentheseDroite_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identif_)
            + toString(this._parentheseGauche_)
            + toString(this._listeExpr_)
            + toString(this._parentheseDroite_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identif_ == child)
        {
            this._identif_ = null;
            return;
        }

        if(this._parentheseGauche_ == child)
        {
            this._parentheseGauche_ = null;
            return;
        }

        if(this._listeExpr_ == child)
        {
            this._listeExpr_ = null;
            return;
        }

        if(this._parentheseDroite_ == child)
        {
            this._parentheseDroite_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identif_ == oldChild)
        {
            setIdentif((TIdentif) newChild);
            return;
        }

        if(this._parentheseGauche_ == oldChild)
        {
            setParentheseGauche((TParentheseGauche) newChild);
            return;
        }

        if(this._listeExpr_ == oldChild)
        {
            setListeExpr((PListeExpr) newChild);
            return;
        }

        if(this._parentheseDroite_ == oldChild)
        {
            setParentheseDroite((TParentheseDroite) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
