/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AListeVarPrime extends PListeVarPrime
{
    private TVirgule _virgule_;
    private PDeclarationVar _declarationVar_;
    private PListeVarPrime _listeVarPrime_;

    public AListeVarPrime()
    {
        // Constructor
    }

    public AListeVarPrime(
        @SuppressWarnings("hiding") TVirgule _virgule_,
        @SuppressWarnings("hiding") PDeclarationVar _declarationVar_,
        @SuppressWarnings("hiding") PListeVarPrime _listeVarPrime_)
    {
        // Constructor
        setVirgule(_virgule_);

        setDeclarationVar(_declarationVar_);

        setListeVarPrime(_listeVarPrime_);

    }

    @Override
    public Object clone()
    {
        return new AListeVarPrime(
            cloneNode(this._virgule_),
            cloneNode(this._declarationVar_),
            cloneNode(this._listeVarPrime_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListeVarPrime(this);
    }

    public TVirgule getVirgule()
    {
        return this._virgule_;
    }

    public void setVirgule(TVirgule node)
    {
        if(this._virgule_ != null)
        {
            this._virgule_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgule_ = node;
    }

    public PDeclarationVar getDeclarationVar()
    {
        return this._declarationVar_;
    }

    public void setDeclarationVar(PDeclarationVar node)
    {
        if(this._declarationVar_ != null)
        {
            this._declarationVar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declarationVar_ = node;
    }

    public PListeVarPrime getListeVarPrime()
    {
        return this._listeVarPrime_;
    }

    public void setListeVarPrime(PListeVarPrime node)
    {
        if(this._listeVarPrime_ != null)
        {
            this._listeVarPrime_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listeVarPrime_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._virgule_)
            + toString(this._declarationVar_)
            + toString(this._listeVarPrime_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._virgule_ == child)
        {
            this._virgule_ = null;
            return;
        }

        if(this._declarationVar_ == child)
        {
            this._declarationVar_ = null;
            return;
        }

        if(this._listeVarPrime_ == child)
        {
            this._listeVarPrime_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._virgule_ == oldChild)
        {
            setVirgule((TVirgule) newChild);
            return;
        }

        if(this._declarationVar_ == oldChild)
        {
            setDeclarationVar((PDeclarationVar) newChild);
            return;
        }

        if(this._listeVarPrime_ == oldChild)
        {
            setListeVarPrime((PListeVarPrime) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
