/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AListeFonc extends PListeFonc
{
    private PDeclarationFonc _declarationFonc_;
    private PListeFonc _listeFonc_;

    public AListeFonc()
    {
        // Constructor
    }

    public AListeFonc(
        @SuppressWarnings("hiding") PDeclarationFonc _declarationFonc_,
        @SuppressWarnings("hiding") PListeFonc _listeFonc_)
    {
        // Constructor
        setDeclarationFonc(_declarationFonc_);

        setListeFonc(_listeFonc_);

    }

    @Override
    public Object clone()
    {
        return new AListeFonc(
            cloneNode(this._declarationFonc_),
            cloneNode(this._listeFonc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListeFonc(this);
    }

    public PDeclarationFonc getDeclarationFonc()
    {
        return this._declarationFonc_;
    }

    public void setDeclarationFonc(PDeclarationFonc node)
    {
        if(this._declarationFonc_ != null)
        {
            this._declarationFonc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declarationFonc_ = node;
    }

    public PListeFonc getListeFonc()
    {
        return this._listeFonc_;
    }

    public void setListeFonc(PListeFonc node)
    {
        if(this._listeFonc_ != null)
        {
            this._listeFonc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listeFonc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declarationFonc_)
            + toString(this._listeFonc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declarationFonc_ == child)
        {
            this._declarationFonc_ = null;
            return;
        }

        if(this._listeFonc_ == child)
        {
            this._listeFonc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declarationFonc_ == oldChild)
        {
            setDeclarationFonc((PDeclarationFonc) newChild);
            return;
        }

        if(this._listeFonc_ == oldChild)
        {
            setListeFonc((PListeFonc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
