/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ANonExpr6 extends PExpr6
{
    private TExclamation _exclamation_;
    private PExpr6 _expr6_;

    public ANonExpr6()
    {
        // Constructor
    }

    public ANonExpr6(
        @SuppressWarnings("hiding") TExclamation _exclamation_,
        @SuppressWarnings("hiding") PExpr6 _expr6_)
    {
        // Constructor
        setExclamation(_exclamation_);

        setExpr6(_expr6_);

    }

    @Override
    public Object clone()
    {
        return new ANonExpr6(
            cloneNode(this._exclamation_),
            cloneNode(this._expr6_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANonExpr6(this);
    }

    public TExclamation getExclamation()
    {
        return this._exclamation_;
    }

    public void setExclamation(TExclamation node)
    {
        if(this._exclamation_ != null)
        {
            this._exclamation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exclamation_ = node;
    }

    public PExpr6 getExpr6()
    {
        return this._expr6_;
    }

    public void setExpr6(PExpr6 node)
    {
        if(this._expr6_ != null)
        {
            this._expr6_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr6_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exclamation_)
            + toString(this._expr6_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exclamation_ == child)
        {
            this._exclamation_ = null;
            return;
        }

        if(this._expr6_ == child)
        {
            this._expr6_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exclamation_ == oldChild)
        {
            setExclamation((TExclamation) newChild);
            return;
        }

        if(this._expr6_ == oldChild)
        {
            setExpr6((PExpr6) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
