/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ATableauVar extends PVar
{
    private TIdentif _identif_;
    private TCrochetGauche _crochetGauche_;
    private PExpr _expr_;
    private TCrochetDroit _crochetDroit_;

    public ATableauVar()
    {
        // Constructor
    }

    public ATableauVar(
        @SuppressWarnings("hiding") TIdentif _identif_,
        @SuppressWarnings("hiding") TCrochetGauche _crochetGauche_,
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") TCrochetDroit _crochetDroit_)
    {
        // Constructor
        setIdentif(_identif_);

        setCrochetGauche(_crochetGauche_);

        setExpr(_expr_);

        setCrochetDroit(_crochetDroit_);

    }

    @Override
    public Object clone()
    {
        return new ATableauVar(
            cloneNode(this._identif_),
            cloneNode(this._crochetGauche_),
            cloneNode(this._expr_),
            cloneNode(this._crochetDroit_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATableauVar(this);
    }

    public TIdentif getIdentif()
    {
        return this._identif_;
    }

    public void setIdentif(TIdentif node)
    {
        if(this._identif_ != null)
        {
            this._identif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identif_ = node;
    }

    public TCrochetGauche getCrochetGauche()
    {
        return this._crochetGauche_;
    }

    public void setCrochetGauche(TCrochetGauche node)
    {
        if(this._crochetGauche_ != null)
        {
            this._crochetGauche_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._crochetGauche_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public TCrochetDroit getCrochetDroit()
    {
        return this._crochetDroit_;
    }

    public void setCrochetDroit(TCrochetDroit node)
    {
        if(this._crochetDroit_ != null)
        {
            this._crochetDroit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._crochetDroit_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identif_)
            + toString(this._crochetGauche_)
            + toString(this._expr_)
            + toString(this._crochetDroit_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identif_ == child)
        {
            this._identif_ = null;
            return;
        }

        if(this._crochetGauche_ == child)
        {
            this._crochetGauche_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._crochetDroit_ == child)
        {
            this._crochetDroit_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identif_ == oldChild)
        {
            setIdentif((TIdentif) newChild);
            return;
        }

        if(this._crochetGauche_ == oldChild)
        {
            setCrochetGauche((TCrochetGauche) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._crochetDroit_ == oldChild)
        {
            setCrochetDroit((TCrochetDroit) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
